// Bake Hand_A/B fixtures into src/scenes/dots/handTargets.data.js (committed).
//   node tools/pmbake/bakeHands.mjs
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { decodePng, toLum } from './png.mjs';
import { importanceSample } from './sample.mjs';
import { packInt16 } from '../../src/scenes/dots/pmCodec.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FIX = join(HERE, 'fixtures');
const OUT = join(HERE, '..', '..', 'src', 'scenes', 'dots', 'handTargets.data.js');
const K = 26000;

function bake(name, seed) {
  const png = decodePng(new Uint8Array(readFileSync(join(FIX, name))));
  const { n, u, v } = importanceSample(toLum(png), K, seed);
  return { n, u: packInt16(u), v: packInt16(v) };
}

const A = bake('Hand_A.png', 101);
const B = bake('Hand_B.png', 202);
const body = `// GENERATED by tools/pmbake/bakeHands.mjs — do not edit by hand.\n` +
  `export const HANDS = ${JSON.stringify({ A, B })};\n`;
writeFileSync(OUT, body);
console.log('wrote', OUT, 'A.n=', A.n, 'B.n=', B.n);
