// Bake the turbulence profile from committed frame fixtures into turbProfile.data.js.
//   node tools/pmbake/extractTurb.mjs
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { decodePng, toLum } from './png.mjs';
import { measureTurb } from './turb.mjs';
import { packUint8 } from '../../src/scenes/dots/pmCodec.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const FRAMES = join(HERE, 'fixtures', 'frames');
const OUT = join(HERE, '..', '..', 'src', 'scenes', 'dots', 'turbProfile.data.js');

const files = readdirSync(FRAMES).filter((f) => f.endsWith('.png')).sort();
const frames = files.map((f) => toLum(decodePng(new Uint8Array(readFileSync(join(FRAMES, f))))));
const p = measureTurb(frames, 64);
const data = {
  dim: p.dim, density: packUint8(p.density),
  flowAngle: +p.flowAngle.toFixed(5), coherence: +p.coherence.toFixed(4),
  scale: +p.scale.toFixed(4), streakLen: +p.streakLen.toFixed(4),
  mean: +p.mean.toFixed(4), contrast: +p.contrast.toFixed(4),
};
writeFileSync(OUT, `// GENERATED by tools/pmbake/extractTurb.mjs — do not edit by hand.\nexport const TURB = ${JSON.stringify(data)};\n`);
console.log('wrote', OUT, 'flowAngle=', data.flowAngle, 'coherence=', data.coherence, 'scale=', data.scale);
